export default interface IFeaturedMedia {
  thumbnail: string,
  medium: string,
  medium_large: string,
  large: string,
  "1536x1536": string,
  "2048x2048": string,
  "big-size": string,
  "big-size_mobile": string,
  "mid-size": string,
  "mid-size_mobile": string,
  "web-stories-poster-portrait": string,
  "web-stories-poster-landscape": string,
  "web-stories-poster-square": string,
  "web-stories-publisher-logo": string,
  "web-stories-thumbnail": string,
}
